# Generated by Django 3.0.3 on 2020-06-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200615_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default', upload_to='media/images'),
        ),
    ]
